### ISSUE TITLE
Consider disabling wysiwyg editor

### ISSUE THREAD

**Issue by scottnelle** [alleyinteractive/logger#3]
When a URL from the site is logged on its own line, the WYSIWYG editor renders it as a post embed. I imagine there will be other cases where things get rendered in unexpected ways in the editor. Consider disabling the WYSIWYG editor (perhaps by filtering `user_can_richedit`) for this post type or removing the editor entirely and outputting the message in a meta box inside of `<pre>` tags (if you don't want the log messages to be editable at all.)

**Comment by srtfisher** [comment]
Resolved in #25
