### ISSUE TITLE
Mantle Framework Dependency intended?

### ISSUE THREAD

**Issue by schuhwerk** [alleyinteractive/logger#43]
Hi! Thanks for open sourcing your logger :) I like your approach!

When checking the requirements the mantle-framework now also appears as a "production"-dependency ([here](https://github.com/alleyinteractive/logger/blob/201201efb229ac4603cc688804c2c35c329e3641/composer.json#L15)).

This additional dependency creates an overhead which makes (the otherwise perfect ;) plugin unusable (for my usecase). I checked the code and it looks like it is just used for testing (so it would be okay to use it as a dev-dependency?). Is this intended or just an oversight?

Thanks for your work!

**Comment by svorwerk-dentsu** [comment]
I second that notion of saying thank you for open sourcing everything you all have open sourced. Clearly you all do amazing work!

I just wanted to mention that the framework looks like it is only used to generate the autoloader. You could extract the autoloader and add it in the appropriate place and then remove the dependency.

Open the file ./inc/bootstrap.php, remove line 10, 
```php
use function Mantle\Framework\generate_wp_autoloader;
```

and replace with:

```php
function generate_wp_autoloader( string $namespace, string $root_path ): callable {
	// Ensure consistent root.
	$root_path = \rtrim( $root_path, \DIRECTORY_SEPARATOR ) . \DIRECTORY_SEPARATOR;
	return function ( $classname ) use ( $namespace, $root_path ) {
		// Ignore if the base namespace doesn't match.
		if ( 0 !== \strpos( $classname, $namespace ) ) {
			return;
		}

		// Remove the namespace.
		$classname = \preg_replace( '#^' . \preg_quote( $namespace, '#' ) . '#', '', $classname );
		$classname = \ltrim( $classname, '\\' );

		// Convert to segments.
		$classname = \strtolower( $classname );
		$classname = \str_replace( [ '\\', '_' ], [ '/', '-' ], $classname );
		$classes   = \explode( '/', $classname );

		// Retrieve the class name (last item).
		$class = \array_pop( $classes );

		// Build the base path.
		$base_path = \implode( '/', $classes );

		// Support multiple locations since the class could be a class, trait or interface.
		$paths = [
			'%1$s/class-%2$s.php',
			'%1$s/trait-%2$s.php',
			'%1$s/interface-%2$s.php',
		];

		/*
		 * Attempt to find the file by looping through the various paths.
		 *
		 * Autoloading a class will also cause a trait or interface with the
		 * same fully qualified name to be autoloaded, as it's impossible to
		 * tell which was requested.
		 */
		foreach ( $paths as $path ) {
			$path = $root_path . \sprintf( $path, $base_path, $class );

			if ( \file_exists($path ) && 0 === validate_file( $path ) ) {
				// Path is defined by this file and validated.
				require_once $path; // phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable
				return;
			}
		}
	};
}
```

You should be good to go from there!

**Comment by srtfisher** [comment]
I plan on switching out the dependency in favor of the newly open-sourced https://github.com/alleyinteractive/wordpress-autoloader
