### ISSUE TITLE
Unable to trash logs

### ISSUE THREAD

**Issue by davidvexel** [alleyinteractive/logger#52]
Hi there!

I noticed that it's not possible to trash the logs, I was trying from the UI and thought there was something wrong with my install, then tried using wp cli and got the following result:

`Warning: Posts of type 'ai_log' do not support being sent to trash.
Please use the --force flag to skip trash and delete them permanently.`

I wanted to kindly ask you if this is intentional? Is there any way to trash logs?

Thanks.

**Comment by srtfisher** [comment]
We're not doing anything to prevent logs from being trashed, it's included with custom post types by default. I'm not able to recreate that issue and I can trash logs properly.

Maybe this is related? https://github.com/wp-cli/entity-command/issues/128 According to the code here https://github.com/wp-cli/entity-command/blob/5fc5e17b54ff0a09ff3bc24da3ac8fc2bc47e6fa/src/Post_Command.php#L496-L503 wp-cli will throw that error message if it isn't a `post` post type.
